# see deeplizard blog 
### has complete course,  except code

In [1]:
import torch

In [2]:
print(torch.__version__)

1.0.1


In [5]:
torch.cuda.is_available()

False

In [7]:
#if true
#torch.version.cuda

## tensosr = nd-array
- rank of a tensor = # of dimensions
- also called the number of axes
- shape of tensor

In [10]:
ara= [[1,2,3],
      [9,7,2]]
t = torch.tensor(ara)
t

tensor([[1, 2, 3],
        [9, 7, 2]])

In [18]:
type(ara)

list

In [12]:
type(t), t.shape , t.size()

(torch.Tensor, torch.Size([2, 3]), torch.Size([2, 3]))

In [13]:
t.reshape(3,2)

tensor([[1, 2],
        [3, 9],
        [7, 2]])

## Pytorch Tensor

In [15]:
t = torch.Tensor()
type(t)

torch.Tensor

### pytroch tensor attributes
- tensors contain uniform datatype
- operation between tensors depend on their datatype and device. they must be on same device.

In [16]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


### create tensors 
- 4 ways

In [2]:
import numpy as np

In [3]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [7]:
t1 = torch.Tensor(data) #Tensor is the constructor 
t1
#uses global default dtype

tensor([1., 2., 3.])

In [8]:
t2 = torch.tensor(data) #tensor is a factory function to create tensors
t2
# rest methods use dtype of the data

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
t3 = torch.as_tensor(data) #factory function
t3

tensor([1, 2, 3], dtype=torch.int32)

In [10]:
t4 = torch.from_numpy(data) #factory function
t4

tensor([1, 2, 3], dtype=torch.int32)

### other ways
- torch.eye(n)
- torch.zeros(n)
- torch.ones(n)
- torch.rand(n)

In [6]:
#explicitly setting dtype
torch.tensor(data,dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

### tensors reaction to changing input data

In [11]:
data[0]=data[1]=data[2]=0
data , t1 , t2 , t3 , t4

(array([0, 0, 0]),
 tensor([1., 2., 3.]),
 tensor([1, 2, 3], dtype=torch.int32),
 tensor([0, 0, 0], dtype=torch.int32),
 tensor([0, 0, 0], dtype=torch.int32))

#### what shit? values changes?
- Tensor and tensor **create** new objects
- as_tensor, from_numpy **share** memory

##### go to option:
- torch.tensor()

##### for performance:
- torch.as_tensor()

## Tensor operation type
- reshape
- elementwise
- reduce
- access

### reshape

In [12]:
t=torch.ones(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
t.shape

torch.Size([3, 4])

In [15]:
#number of elements
torch.tensor(t.shape).prod() , t.numel()

(tensor(12), 12)

In [16]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [17]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [18]:
#squeezing removes all axes with length of 1

p = t.reshape(1,12).squeeze()
p , p.shape

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), torch.Size([12]))

In [20]:
p = t.reshape(3,1,4).squeeze()
p , p.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.Size([3, 4]))

In [22]:
#unsqueeze removes all the axes with the length of 1
p = p.unsqueeze(dim=0)
p , p.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]), torch.Size([1, 3, 4]))

In [27]:
def flatten(t):
    return t.reshape(1,-1).squeeze()

In [25]:
t.shape

torch.Size([3, 4])

In [28]:
p = flatten(t)
p , p.shape

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), torch.Size([12]))

In [35]:
t1=torch.ones(2,3)
t2=2*torch.ones(2,3)
t3=3*torch.ones(2,3)

t = torch.stack((t1,t2,t3))

In [36]:
t , t.shape

(tensor([[[1., 1., 1.],
          [1., 1., 1.]],
 
         [[2., 2., 2.],
          [2., 2., 2.]],
 
         [[3., 3., 3.],
          [3., 3., 3.]]]), torch.Size([3, 2, 3]))

In [37]:
#flatten the images, leaving out the batches
p = t.flatten(start_dim=1)
p , p.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 3.]]), torch.Size([3, 6]))

### element wise

In [38]:
t1 + t2

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [42]:
print(t1 + 4)
print(t1.add(4))
#sub, mul, div

tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [56]:
t4 = torch.tensor([1,2,3] , dtype=torch.float32)

In [57]:
t1 + t4 #broadcasting

tensor([[2., 3., 4.],
        [2., 3., 4.]])

In [59]:
np.broadcast_to(t4.numpy(),t1.shape) #donno why he did this

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

### comparisons

In [63]:
t4 <= 2

tensor([1, 1, 0], dtype=torch.uint8)

### reduction operations

In [67]:
t1 = torch.rand(3,5)
t1

tensor([[0.4158, 0.7485, 0.7809, 0.1221, 0.5490],
        [0.9008, 0.2064, 0.5957, 0.7044, 0.6662],
        [0.1433, 0.7833, 0.6490, 0.1143, 0.0266]])

In [68]:
t1.sum()

tensor(7.4062)

In [69]:
t1.mean()

tensor(0.4937)

In [70]:
t1.std()

tensor(0.2952)

In [71]:
t1.sum(dim=0)

tensor([1.4599, 1.7381, 2.0255, 0.9408, 1.2418])

In [72]:
t1.sum(dim=1)

tensor([2.6163, 3.0735, 1.7164])

In [73]:
t1.argmax() #returns position the element, index from flatten

tensor(5)

In [76]:
t1.max() , t1.max().item() #get the value

(tensor(0.9008), 0.9008330702781677)

In [75]:
t1.argmax(dim=1)

tensor([2, 0, 1])

- .item()
- .tolist()
- .numpy()