# See deeplizard blog 
### Has complete course,  except code
### Also is updated

## Install
- go to pytorch website
- select configs
- download
- no need to download cuda separately, it comes with pytorch

## Pytorch

In [0]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.1.0


In [3]:
torch.cuda.is_available()

True

In [4]:
#if true
torch.version.cuda

'10.0.130'

- Cpus have 4,8,16 cores, gpus have thousands of core. A task can only be parallelized upto how many cores there are.
- NNs are 'Embarassingly parallel'. meaning it takes little to no effort to break down tasks into similar parallel tasks.
- cuda is the software layer that provides an api for the developers. gpu being the hardware layer.
- most of pytorch in written in python(thus debugging is easier), at bottleneck points, it drops to c/c++ for performance boosts.

## Using CUDA

In [5]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [6]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

- Why not run all computations on the gpu?
- GPU is only faster in some tasks.
- Moving from CPU to GPU is costly, so for simple tasks, the overall cost may become negative.
- **Paper**: GPGPU computing (29 Aug 2014)

## tensosr = nd-array
- rank of a tensor = # of dimensions
- also called the number of axes
- shape of tensor

In [7]:
## 0-dim tensor, or scalar
s = torch.tensor(4)
s, s.shape

(tensor(4), torch.Size([]))

In [8]:
ara= [[1,2,3],
      [9,7,2]]
t = torch.tensor(ara)
t

tensor([[1, 2, 3],
        [9, 7, 2]])

In [9]:
type(ara)

list

In [10]:
type(t), t.shape , t.size()

(torch.Tensor, torch.Size([2, 3]), torch.Size([2, 3]))

In [11]:
t.reshape(3,2)

tensor([[1, 2],
        [3, 9],
        [7, 2]])

## Pytorch Tensor

In [12]:
t = torch.Tensor()
type(t)

torch.Tensor

### pytroch tensor attributes
- tensors contain uniform datatype
- operation between tensors depend on their datatype and device. they must be on same device.

In [14]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


### devices
- pytorch supports multiple devices

In [15]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [16]:
torch.device('cuda:1') 
#can;t use it though, cause we dont have more gpu

device(type='cuda', index=1)

### create tensors 
- 4 ways

In [0]:
import numpy as np

In [18]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [19]:
t1 = torch.Tensor(data) #Tensor is the constructor 
t1
#uses global default dtype (float)

tensor([1., 2., 3.])

In [28]:
torch.get_default_dtype()

torch.float32

In [21]:
t2 = torch.tensor(data) #tensor is a factory function to create tensors
t2, t2.dtype
# rest methods use dtype of the data

(tensor([1, 2, 3]), torch.int64)

In [24]:
t3 = torch.as_tensor(data) #factory function
t3, t3.dtype

(tensor([1, 2, 3]), torch.int64)

In [23]:
t4 = torch.from_numpy(data) #factory function
t4, t4.dtype

(tensor([1, 2, 3]), torch.int64)

### other ways
- torch.eye(n)
- torch.zeros(n,m)
- torch.ones(n,m)
- torch.rand(n,m)

In [29]:
#explicitly setting dtype
torch.tensor(data,dtype=torch.float64) #this functionality is not present for the constructor

tensor([1., 2., 3.], dtype=torch.float64)

### tensors reaction to changing input data

In [30]:
data[0]=data[1]=data[2]=0
data , t1 , t2 , t3 , t4

(array([0, 0, 0]),
 tensor([1., 2., 3.]),
 tensor([1, 2, 3]),
 tensor([0, 0, 0]),
 tensor([0, 0, 0]))

#### what shit? values changes?
- Tensor and tensor **create** new objects
- as_tensor, from_numpy **share** memory

#### go to option:
- torch.tensor()

#### for performance:
- torch.as_tensor()
- because it can accept any array like object, not just numpy array

## Tensor operation type
- reshape
- elementwise
- reduce
- access

### reshape

In [31]:
t=torch.ones(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
t.shape

torch.Size([3, 4])

In [33]:
#number of elements
torch.tensor(t.shape).prod() , t.numel()

(tensor(12), 12)

In [34]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [35]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

### Squeeze

In [36]:
#squeezing removes all axes with length of 1

p = t.reshape(1,12).squeeze()
p , p.shape

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), torch.Size([12]))

In [38]:
t.reshape(3,1,4)

tensor([[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]])

In [41]:
p = t.reshape(3,1,4).squeeze()
p , p.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.Size([3, 4]))

### Unsqueeze

In [42]:
#unsqueeze removes all the axes with the length of 1
q = p.unsqueeze(dim=0)
q , q.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]), torch.Size([1, 3, 4]))

In [43]:
r = p.unsqueeze(dim=1)
r , r.shape

(tensor([[[1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.]]]), torch.Size([3, 1, 4]))

### Flatten

In [0]:
def flatten(t):
    return t.reshape(1,-1).squeeze()

In [45]:
t.shape

torch.Size([3, 4])

In [46]:
p = flatten(t)
p , p.shape

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), torch.Size([12]))

In [48]:
## flattening using only reshape operation
p = t.reshape(-1)
p, p.shape

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), torch.Size([12]))

### Concatination, Stack

In [49]:
t1=torch.ones(2,3)
t2=2*torch.ones(4,3)
torch.cat((t1,t2),dim=0) #only the dim mentioned can have different values in the input tensors

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [0]:
t1=torch.ones(2,3)
t2=2*torch.ones(2,3)
t3=3*torch.ones(2,3)

t = torch.stack((t1,t2,t3))

In [51]:
t , t.shape

(tensor([[[1., 1., 1.],
          [1., 1., 1.]],
 
         [[2., 2., 2.],
          [2., 2., 2.]],
 
         [[3., 3., 3.],
          [3., 3., 3.]]]), torch.Size([3, 2, 3]))

### Flatten Images

In [52]:
t.shape

torch.Size([3, 2, 3])

In [0]:
t = t.reshape(3,1,2,3) #Imagine it to be a batch Gray Scale image

In [54]:
#flatten the images, leaving out the batches
p = t.flatten(start_dim=1)
p , p.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 3.]]), torch.Size([3, 6]))

In [55]:
q = t.flatten(start_dim=2)
q, q.shape, t.shape

(tensor([[[1., 1., 1., 1., 1., 1.]],
 
         [[2., 2., 2., 2., 2., 2.]],
 
         [[3., 3., 3., 3., 3., 3.]]]),
 torch.Size([3, 1, 6]),
 torch.Size([3, 1, 2, 3]))

### element wise

In [56]:
t1.shape, t2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [57]:
t1 + t2

tensor([[3., 3., 3.],
        [3., 3., 3.]])

### broadcasting

In [59]:
## we can see what the broadcasted value looks like
np.broadcast_to(4,t1.shape)

array([[4, 4, 4],
       [4, 4, 4]])

In [60]:
print(t1 + 4)
print(t1.add(4))
#sub, mul, div

tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [0]:
t4 = torch.tensor([1,2,3] , dtype=torch.float32)

In [62]:
t1, t4

(tensor([[1., 1., 1.],
         [1., 1., 1.]]), tensor([1., 2., 3.]))

In [63]:
t1 + t4 #broadcasting (lower rank tensor is broadcasted to match the higher rank of the tensor)

tensor([[2., 3., 4.],
        [2., 3., 4.]])

In [64]:
np.broadcast_to(t4.numpy(),t1.shape) #this is how it was broadcasted

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

### comparisons

In [65]:
t4 <= 2

tensor([1, 1, 0], dtype=torch.uint8)

In [67]:
t4.le(2)

tensor([1, 1, 0], dtype=torch.uint8)

### element wise comparison
- t.eq(1)
- t.ge(1)
- t.gt(0)
- t.lt(0)
- t.le(0)

### element wise funcs
- t.abs()
- t.sqrt()
- t.neg()

### reduction operations

In [68]:
t1 = torch.rand(3,5)
t1

tensor([[0.8001, 0.4027, 0.0621, 0.2939, 0.7122],
        [0.1465, 0.1640, 0.0184, 0.5465, 0.0426],
        [0.3010, 0.0352, 0.2819, 0.8323, 0.1359]])

In [69]:
t1.sum()

tensor(4.7752)

In [70]:
t1.mean()

tensor(0.3183)

In [71]:
t1.std()

tensor(0.2817)

In [74]:
t1.prod()

tensor(1.4557e-11)

In [75]:
t1.sum(dim=0)

tensor([1.2476, 0.6018, 0.3624, 1.6728, 0.8906])

In [76]:
t1.sum(dim=1)

tensor([2.2709, 0.9179, 1.5863])

In [77]:
t1.argmax() #returns position the element, index from flatten

tensor(13)

In [78]:
t1.max() , t1.max().item() #get the value

(tensor(0.8323), 0.8323473334312439)

In [80]:
t1.argmax(dim=1)

tensor([0, 3, 3])

- .item()
- .tolist()
- .numpy()