Concatenating joins a sequence of tensors along an **existing exis**, and Stacking joins a sequence of tensors along a **new axis**.

We will see it in
- pytoch
- numpy
- tensorflow

## adding axis

In [0]:
import torch
t1 = torch.tensor([1,1,1])

In [2]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [4]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [5]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


## in pytorch

In [0]:
import torch

t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [7]:
torch.cat(
    (t1,t2,t3)
    ,dim=0
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [8]:
torch.stack(
    (t1,t2,t3)
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [10]:
## stacking = new_axis_creation + cat
torch.cat(
    (
         t1.unsqueeze(0)
        ,t2.unsqueeze(0)
        ,t3.unsqueeze(0)
    )
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [11]:
torch.stack(
    (t1,t2,t3)
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [12]:
torch.cat(
    (
         t1.unsqueeze(1)
        ,t2.unsqueeze(1)
        ,t3.unsqueeze(1)
    )
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

## in tensorflow

In [0]:
import tensorflow as tf

t1 = tf.constant([1,1,1])
t2 = tf.constant([2,2,2])
t3 = tf.constant([3,3,3])

In [16]:
tf.concat(
    (t1,t2,t3)
    ,axis=0
)

<tf.Tensor 'concat_2:0' shape=(9,) dtype=int32>

In [17]:
tf.stack(
    (t1,t2,t3)
    ,axis=0
)

<tf.Tensor 'stack:0' shape=(3, 3) dtype=int32>

In [18]:
tf.concat(
    (
         tf.expand_dims(t1, 0)
        ,tf.expand_dims(t2, 0)
        ,tf.expand_dims(t3, 0)
    )
    ,axis=0
)

<tf.Tensor 'concat_3:0' shape=(3, 3) dtype=int32>

In [19]:
tf.concat(
    (
         tf.expand_dims(t1, 1)
        ,tf.expand_dims(t2, 1)
        ,tf.expand_dims(t3, 1)
    )    
    ,axis=1
)

<tf.Tensor 'concat_4:0' shape=(3, 3) dtype=int32>

In [20]:
tf.stack(
    (t1,t2,t3)
    ,axis=1
)

<tf.Tensor 'stack_1:0' shape=(3, 3) dtype=int32>

## in numpy

In [0]:
import numpy as np

t1 = np.array([1,1,1])
t2 = np.array([2,2,2])
t3 = np.array([3,3,3])

In [25]:
np.concatenate(
    (t1,t2,t3)
    ,axis=0
)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [26]:
np.stack(
    (t1,t2,t3)
    ,axis=0
)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [27]:
np.concatenate(
    (
         np.expand_dims(t1, 0)
        ,np.expand_dims(t2, 0)
        ,np.expand_dims(t3, 0)
    )
    ,axis=0
)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [30]:
np.stack(
    (t1,t2,t3)
    ,axis=1
)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
np.concatenate(
    (
         np.expand_dims(t1, 1)
        ,np.expand_dims(t2, 1)
        ,np.expand_dims(t3, 1)
    )
    ,axis=1
)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])